[package]
name = "hxa-conv"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hxa = { version = "0.1.0", path = "../" }
obj = "0.10.2"
pico-args = "0.4.2"
